
server:
  port: 9445
  ssl:
    key-store: classpath:keystore/keystore.jks
    key-store-type: jks
    key-store-password: password
    key-alias: ssl
    enabled: true

security:
  basic:
    username: user
    password: password
    enabled: false
  csrf:
    enabled: false

management:
  server:
    port: 9446
    address: 127.0.0.1
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans

spring:
  application:
    name: XML/JSON to PDF (si-xml-to-pdf-jar)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: user
        password: password

logging:
  file:
    name: logfile.txt